### ISSUE TITLE
After build, css doesn't work

### ISSUE THREAD

**Issue by tranvanhieu01012002** [erbelion/tutorial-vite-plugin-laravel-purgecss#1]
I ran your example and it can reduce css size, but css doesn't work
Build with ```laravel``` only
![image](https://github.com/user-attachments/assets/94a08f86-f7e3-4ccd-9e12-b8584260240a)

Build with ```"@erbelion/vite-plugin-laravel-purgecss": "^0.3.2"```
![image](https://github.com/user-attachments/assets/c54a98df-0da5-4fd7-a942-9cce49e95ca2)

this is ```vite.config.js```

```
import { defineConfig } from "vite";
import laravel from "laravel-vite-plugin";
import purge from "@erbelion/vite-plugin-laravel-purgecss";

export default defineConfig({
    plugins: [
        laravel({
            input: ["resources/sass/app.scss", "resources/js/app.js"],
            refresh: true,
        }),
        purge(["resources/views/welcome.blade.php"])
    ],
});

```

**Comment by erbelion** [comment]
to make it work, you must either specify the paths to purge like this:

```
export default defineConfig({
    plugins: [
        laravel(...),
        purge({
            paths: ["resources/views/**/*.blade.php"]
        })
    ]
})
```

or don't specify the paths at all and let the plugin default it to `resources/{js,views}/**/*.{blade.php,svelte,vue,html}`:
```
export default defineConfig({
    plugins: [
        laravel(...),
        purge()
    ]
})
```
when trying out your way i realized, that path defaulting didn't work in 0.3.2. its now fixed as of 0.3.3
